static/css/screen.css
=> css for logout button

static/css/dashboard.css
CSS changes to make scrollbars in html forms in small devices more visible.
=> Eperez master

react/src/components/Security.js
=> show localtime

react/src/actions/common.js, react/src/init-app.js, react/src/init-config.js, react/src/sagas/ChangePassword.js, react/src/sagas/Config.js, react/src/sagas/Emails.js, react/src/sagas/LetterProofing.js, react/src/sagas/Mobile.js, react/src/sagas/Nins.js, react/src/sagas/OpenidConnect.js, react/src/sagas/OpenidConnectFreja.js, react/src/sagas/PersonalData.js, react/src/sagas/Security.js
Direct user to token service whenever there is an unauthn request
=> Eperez unauthn

react/headless.karma.conf.js, react/karma.conf.js, react/src/actions/common.js, react/src/entry-points/openid-connect-freja.js, react/src/init-app.js, react/src/init-config.js, react/src/sagas/Config.js, react/webpack.config.js
Allow embedding the freja button into the old dashboard
=> Freja temp

react/src/entry-points/openid-connect-freja.js, react/src/init-app.js, react/webpack.config.js, react/webpack.prod.config.js
Fix Freja component, so it doesn't disappear and it is localized.
=> Eperez vanishing freja

.travis.yml, react/src/tests/Emails-test.js, react/src/tests/Mobile-test.js, react/src/tests/PersonalData-test.js
Tests are passing now in travis with disabled cache for node modules
=> Eperez fix tests

.travis.yml, react/package.json, react/webpack.config.js, react/webpack.prod.config.js, react/webpack.staging.config.js
Build 3 bundles, one for development, one for staging, and one for production, with different public urls
=> Eperez asset urls

react/src/actions/Mobile.js, react/src/actions/common.js, react/src/components/Mobile.js, react/src/containers/Mobile.js, react/src/reducers/Mobile.js, react/src/sagas/Emails.js, react/src/sagas/Mobile.js, react/src/sagas/PersonalData.js, react/src/tests/Emails-test.js, react/src/tests/Mobile-test.js, react/src/tests/PersonalData-test.js
Show field errors received from the server below fields in the forms.
Not including the NINs tab, since we have a form there for each button, and with proper validation in the client and a single user input, we should not need it.
Same goes for forms in modals.
=> Eperez field errors

react/src/actions/Mobile.js, react/src/actions/common.js, react/src/components/Mobile.js, react/src/containers/Mobile.js, react/src/init-app.js, react/src/reducers/Mobile.js, react/src/sagas/Emails.js, react/src/sagas/Mobile.js, react/src/sagas/PersonalData.js, react/src/tests/Emails-test.js, react/src/tests/Mobile-test.js, react/src/tests/PersonalData-test.js
Do not check for session cookie before rendering, and lean on the request to jsconfig to redirect to authn.
=> Eperez no cookie check

react/src/actions/Mobile.js, react/src/actions/common.js, react/src/components/LetterProofing.js, react/src/components/Mobile.js, react/src/components/Nins.js, react/src/components/OpenidConnect.js, react/src/containers/Mobile.js, react/src/init-app.js, react/src/reducers/Mobile.js, react/src/sagas/Emails.js, react/src/sagas/Mobile.js, react/src/sagas/PersonalData.js, react/src/tests/Emails-test.js, react/src/tests/Mobile-test.js, react/src/tests/PersonalData-test.js, react/src/vetting-registry.js
disable NIN buttons rather than hide them while the NIN is not valid
=> Eperez disabled buttons

react/src/components/Main.js, react/src/entry-points/index.js, react/src/entry-points/openid-connect-freja.js, react/src/style/Main.scss
=> Eperez fixes

react/package-lock.json, react/src/actions/common.js, react/src/entry-points/index.js, react/src/sagas/ChangePassword.js, react/src/sagas/Config.js, react/src/sagas/Emails.js, react/src/sagas/Header.js, react/src/sagas/LetterProofing.js, react/src/sagas/LookupMobileProofing.js, react/src/sagas/Mobile.js, react/src/sagas/Nins.js, react/src/sagas/OpenidConnect.js, react/src/sagas/OpenidConnectFreja.js, react/src/sagas/PersonalData.js, react/src/sagas/Security.js
Some fixes for ie11 and edge, everything seems to be working now in those browsers
=> Eperez iefixes

react/src/components/Footer.js, react/src/style/Footer.scss
Missing style: cursor, display
=> missing style

react/src/components/Nins.js, react/src/containers/LookupMobileProofing.js, react/src/sagas/LookupMobileProofing.js, react/src/sagas/OpenidConnect.js, react/src/sagas/OpenidConnectFreja.js, react/src/sagas/PersonalData.js
This fixes the problem with lookup mobile vetting that sent 'testing' as nin, an a further problem uncovered when fixing that
=> Eperez phone proofing

react/src/containers/Header.js
Show primary email in top right corner
=> show primary email

react/src/containers/Header.js
Show unconfirmed identity when there is no verified nin
=> unconfirmed identity when no verified nin

react/src/components/EduIDButton.js, react/src/style/EduIDButton.scss, react/src/tests/EduIDButton-test.js
Remove ghost spinner from buttons when not spinning
=> Eperez fix spinner

react/src/actions/common.js
Fix problem where a single error message was treated as a form error
=> fix problem where a single error message was treated as a form error

react/src/actions/common.js
HTTP Headers for fetch requests
=> fetch headers

react/src/reducers/PersonalData.js, react/src/tests/PersonalData-test.js
avoid dissapearance of eppn on data save
=> Eperez vanishing eppn

react/src/components/PersonalData.js, react/src/containers/PersonalData.js
touch language field if it is the only empty field
=> touch language field if it is the only empty field

react/src/actions/Notifications.js, react/src/components/OpenidConnectFreja.js, react/src/containers/Emails.js, react/src/containers/LetterProofing.js, react/src/containers/Mobile.js, react/src/containers/OpenidConnectFreja.js, react/src/containers/Security.js, react/src/reducers/Notifications.js, react/src/tests/LetterProofing-test.js, react/src/tests/Security-test.js
Remove notifications when opening modal dialogs
=> Eperez modal nomsg

react/src/components/EduIDTextInput.js
only show validation state after validation
=> only show validation state after validation

react/src/entry-points/openid-connect-freja.js
polyfill for ie11 for the old dashboard
=> polyfill for ie11 for the old dashboard

react/src/sagas/Header.js, react/src/tests/Header-test.js
Expect a 302 response on logout rather than a 200 + json
=> Eperez logout redirect

react/package-lock.json, react/package.json, react/src/entry-points/index.js, react/src/init-app.js
old IE11 has no URL.searchParams
=> old IE11 has no URL.searchParams

react/src/sagas/Header.js
=> fix logout for IE11

react/i18n/src/i18n-messages.json, react/package-lock.json, react/package.json, react/src/i18n-messages.js
Upgrade the u2f-api library
Add a couple of missing translatable strings
=> Eperez u2f

react/i18n/src/i18n-messages.json, react/src/actions/Security.js, react/src/components/ConfirmModal.js, react/src/components/Emails.js, react/src/components/LetterProofing.js, react/src/components/Mobile.js, react/src/components/Security.js, react/src/containers/Security.js, react/src/i18n-messages.js, react/src/reducers/Security.js, react/src/sagas/Security.js, react/src/tests/Security-test.js
Add descriptions to U2F tokens
=> Eperez u2f description

react/src/actions/common.js
Add custom header to AJAX requests
=> check origin in CSRF protection

static/css/actions.css
=> some style for the u2f page

react/package-lock.json, react/package.json, react/src/components/CookieChecker.js, react/src/components/OpenidConnect.js, react/src/tests/CookieChecker-test.js
Component that checks for a cookie and only renders its children if the cookie is not present of the contents do not match a given pattern.
Also upgrading node-sass which was giving me problems
=> Eperez cookie checker

react/src/containers/Security.js, react/src/tests/Security-test.js
remove notifications when adding new security keys
=> remove notifications when adding new security keys

docker/start.sh
correct path for signup bundle
=> correct path for signup bundle

react/src/sagas/Security.js
restore non-fetching state on error adding webauthn token
=> restore non-fetching state on error

react/src/sagas/Security.js, react/src/tests/Security-test.js
=> Eperez cbor json

react/i18n/l10n/en.json, react/i18n/l10n/sv.json, react/i18n/src/i18n-messages.json, react/src/components/Security.js, react/src/i18n-messages.js, react/src/tests/Security-test.js
Remove u2f or webauthn tokens - only if there are more than one
=> Eperez rm tokens

react/src/sagas/Security.js
=> better names

react/src/sagas/Security.js
Do not re-add padding to b64 decode
=> do not re-add padding

en/index.html, static/css/index.css, static/css/reset.css
Background: Home page needs updating in line with new style.
> I know that this styling follows a layout that is a little different than the dashboard and signup (spacing is tighter), but over time my plan is to adopt this style for the other sections as well  
Summary: 
- homepage updated according to layout suggestion shared last week
- a separate index.css file added (as previously modified css files in this repo have required pseudo elements that are not necessary here) 
- Swedish version is still in previous format but can easily be updated and merged separately
- FAQ will be addressed in a separate branch
=> Adds updated home page (Eng only)

en/faq.html, static/css/index.css
Background: Styling of FAQ needs to be updated 
Summary: 
- Updated style applied to page 
- Some large answers have been split up and questions have been added to them
- Statements have been re-written into questions
- Outdated answers (describing the old layout have been removed)
=> Adds new styling to FAQ (Eng)

static/css/login.css, static/css/screen.css
Summary: 
- I have removed the information links from the log in page (because they were removed from the home page) 
- FAQ still visible in the bottom corner 
- I have simplified the css by only including one line in the white banner (the tagline from the homepage)
- I have also added more consistent paddings and margins (set for the home page)
- I have also applied the same styles for the static reset password and error pages
=> Updates login page with styling from home page

static/css/index.css
Background: Our exciting new home page and FAQ need some mobile styling.
Summary: 
- same width styles applied as for dashboard and signup
=> Adds mobile styles to FAQ and homepage 

en/index.html, index.html, static/css/index.css
**Background**:  Making the footers consistent
**Summary**:  I have added in the copyright to left corner of the footer on the home page (Eng and Swe versions)
=> Update Home footer with copyright

en/faq.html, en/index.html, faq.html, index.html, static/css/index.css
**Summary:** 
- Adds brand new question: What are the selected methods of verifying an id number for eduID?
- Intended to address information lost about each of the vetting methods (available in the middle of the old question)
- Adds in styling for a bulleted list
---
---
=> Adds FAQ question: What are the selected methods of verifying an id number for eduID?

en/faq.html, faq.html
Updated info that support will only be carried out via email over summer (weeks 28-31).
Summary: 
- Commented out info about phone support
- Replaced phone info with line about email only period
---
---
=> FAQ: Update info to email-only support (during summer)

en/index.html, index.html, static/css/login.css
Changed copyright year 2013-2019 -> 2013-2021
---
---
=> FOOTER:Changed copyright 2021

en/faq.html, en/index.html, faq.html, index.html
=> prettier format

en/faq.html, en/index.html, faq.html, index.html, static/css/login.css
=> Eunju copyright 2022

en/index.html, index.html
=> Add link to eduID logo

en/index.html, index.html, static/css/index.css
=> Add Sunet logo in footer and login button in header

en/index.html, index.html
=> correct html close tag

static/css/index.css
=> edits paddings in header/footer

en/index.html, index.html, static/css/index.css
=> minor fix (paddings, footer border)

en/faq.html, faq.html, static/css/index.css
=> Update faq 

en/faq.html, en/index.html, faq.html, index.html, static/css/index.css
Further tweaks to exactly match header and footer with app, 
larger tagline for effect and stylishness..
=> Matching header and footer with app

static/css/index.css
=> Updated to accesible colors, slight button update

en/faq.html, en/index.html, faq.html, index.html
Hover and screenreader texts for eduID and Sunet logos.
=> Accesible logos

static/css/index.css
=> Matching spacing updates in app

static/css/index.css
=> Revert "Matching spacing updates in app"

static/css/index.css, static/img/eduID-logo.svg
=> Updated eduID logo format and responsive header css to match app.

en/faq.html, faq.html, static/css/index.css
New list structure with dividers and grouping headings.
Reorganized related content.
Simple in page scrolling nav for desktop, tablet and mobile.
eIDAS help text.
Formatted contact section with html5 mail and phone links.
=> Eidas copy

en/faq.html, en/index.html, faq.html, index.html, static/css/login.css
=> Change copyright 2022->2023

en/faq.html, faq.html
=> Add svipe text

en/faq.html, faq.html
=> Update based on Zacharias's feedback

en/index.html, index.html
=> Update copyright year
